### ISSUE TITLE
Spam email from Napptive

### ISSUE THREAD

**Issue by hoffa** [napptive/catalog-cli#36]
I received unsolicited spam mail from Napptive:

> We have been scouting open source projects in order to provide core project contributors like you with our Pro Edition completely free, without any commitment. At Napptive our mission is to empower you with a self-service platform that speeds up and helps your development projects.

I did not opt in to your marketing.

I don’t know what this project is (and now I couldn’t care in the least), but shame on you for these trashy marketing techniques.

**Comment by dvzkz7** [comment]
Dear hoffa,
We would like to apologize for having reached out to you like this. We completely understand your take on it, and for this reason, we can assure you we have ceased to reach out in this way. We remain at your disposal to further clarify any doubts on this matter.

**Comment by hoffa** [comment]
Thanks, I appreciate it.
